API:
  token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJkZWZhdWx0XzE1IiwiaWF0IjoxNjk1MDI5Mzc4LjMxMzM4NCwibmJmIjoxNjk1MDI5Mzc4LjMxMzM4NCwiZXhwIjoxNjk1MDM2NTc4LjMxMzM4NCwiaWQiOjE1LCJ1c2VybmFtZSI6IuWGr-iLl-W_lyIsInVzZXJfdHlwZSI6IjEwMCIsIm5pY2tuYW1lIjoiMTExIiwicGhvbmUiOiI5NTI3IiwiZW1haWwiOiIyMTMiLCJhdmF0YXIiOm51bGwsInNpZ25lZCI6IjEyMyIsImRhc2hib2FyZCI6bnVsbCwiZGVwdF9pZCI6bnVsbCwic3RhdHVzIjoxLCJsb2dpbl9pcCI6IjE0LjE5LjE3LjIxOCIsImxvZ2luX3RpbWUiOiIyMDIzLTA5LTE4IDE3OjI3OjQ3IiwiYmFja2VuZF9zZXR0aW5nIjpudWxsLCJjcmVhdGVkX2J5IjoxLCJ1cGRhdGVkX2J5IjoxNSwiY3JlYXRlZF9hdCI6IjIwMjMtMDktMDEgMDk6NTQ6MTkiLCJ1cGRhdGVkX2F0IjoiMjAyMy0wOS0xOCAxNzoyNzo0NyIsInJlbWFyayI6bnVsbCwiY29kZSI6IiIsImp3dF9zY2VuZSI6ImRlZmF1bHQifQ.aU-xGffdcF6vZcUZSMCbAA60j9mP4vIcIQtIVUkp6VI
browser:
  browser_name: edge
default_login:
  password: Ceshi123
  username: admin
environment:
  test_url: http://xctestadmin.xczxwe.com/
log:
  console_log_format: '[%(asctime)s] %(filename)s->%(funcName)s line:%(lineno)d [%(levelname)s]
    %(message)s'
  console_log_level: info
  file_log_format: '[%(asctime)s] %(filename)s->%(funcName)s line:%(lineno)d [%(levelname)s]
    %(message)s'
  file_log_level: info
  log_name: log_
report:
  report_name: report_
url:
  login_url: http://admintest.xczxwe.com/admin/login.html
  ui_test_url: https://www.so.com/
