# curl 'http://xctestadmin.xczxwe.com/prod/system/login'
#  -H 'Accept: application/json, text/plain, */*'
#  -H 'Accept-Language: zh_CN'
#  -H 'Authorization: Bearer null'
#  -H 'Content-Type: application/json;charset=UTF-8'
#  -H 'Origin: http://xctestadmin.xczxwe.com'
#  -H 'Proxy-Connection: keep-alive'
#  -H 'Referer: http://xctestadmin.xczxwe.com/'
#  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36'
#  --data-raw '{"username":"∑Î√Á÷æ","password":"123456","code":"wa4b"}'
#  --compressed \
POST http://xctestadmin.xczxwe.com/prod/system/login
Accept: application/json, text/plain, */*
Accept-Language: zh_CN
Authorization: Bearer null
Origin: http://xctestadmin.xczxwe.com
Proxy-Connection: keep-alive
Referer: http://xctestadmin.xczxwe.com/
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Content-Type: application/json;charset=UTF-8

{"username":"∑Î√Á÷æ","password":"123456","code":"wa4b"}

###
###

POST http://xctestadmin.xczxwe.com/prod/system/login
Accept: application/json, text/plain, */*
Accept-Language: zh_CN
Authorization: Bearer null
Origin: http://xctestadmin.xczxwe.com
Proxy-Connection: keep-alive
Referer: http://xctestadmin.xczxwe.com/
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Content-Type: application/json;charset=UTF-8

{"username":"∑Î√Á÷æ","password":"123456"}


###




###


